#!/bin/bash

# Render Deployment Script
echo "🚀 Preparing for Render deployment..."

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}📋 Render Deployment Instructions:${NC}"
echo ""
echo -e "${YELLOW}1. Go to Render Dashboard:${NC}"
echo "   https://dashboard.render.com"
echo ""
echo -e "${YELLOW}2. Sign up/Login:${NC}"
echo "   - Create a free account"
echo "   - Connect your GitHub account"
echo ""
echo -e "${YELLOW}3. Create New Web Service:${NC}"
echo "   - Click 'New +'"
echo "   - Select 'Web Service'"
echo "   - Connect your GitHub repository"
echo ""
echo -e "${YELLOW}4. Configure Service:${NC}"
echo "   - Name: lms-app (or your preferred name)"
echo "   - Environment: Node"
echo "   - Region: Choose closest to you"
echo "   - Branch: main"
echo "   - Root Directory: (leave empty)"
echo ""
echo -e "${YELLOW}5. Build & Deploy Settings:${NC}"
echo "   - Build Command:"
echo "     composer install --no-dev --optimize-autoloader && npm ci && npm run build && php artisan key:generate --force && php artisan migrate --force && php artisan storage:link && php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan optimize"
echo ""
echo "   - Start Command:"
echo "     php artisan serve --host=0.0.0.0 --port=\$PORT"
echo ""
echo -e "${YELLOW}6. Environment Variables:${NC}"
echo "   Add these environment variables:"
echo "   - APP_ENV = production"
echo "   - APP_DEBUG = false"
echo "   - DB_CONNECTION = sqlite"
echo "   - CACHE_STORE = file"
echo "   - SESSION_DRIVER = file"
echo "   - QUEUE_CONNECTION = database"
echo "   - LOG_CHANNEL = stderr"
echo ""
echo -e "${YELLOW}7. Advanced Settings:${NC}"
echo "   - Health Check Path: /health"
echo "   - Auto-Deploy: Yes"
echo ""
echo -e "${GREEN}✅ Configuration files are ready!${NC}"
echo ""
echo -e "${BLUE}📁 Files created:${NC}"
echo "   - render.yaml (Render configuration)"
echo "   - env.production (Production environment template)"
echo ""
echo -e "${BLUE}🔗 Your app will be available at:${NC}"
echo "   https://your-app-name.onrender.com"
echo ""
echo -e "${YELLOW}⚠️  Important Notes:${NC}"
echo "   - Free tier has limitations (sleep after 15 minutes of inactivity)"
echo "   - Database will be SQLite (stored in filesystem)"
echo "   - Files uploaded will be stored in Render's filesystem"
echo "   - Consider upgrading to paid plan for production use"
